[env]
CONTROLLER_CERT_FILE="D:\\data\\certs\\controller\\ca.crt"
CONTROLLER_DOMAIN_NAME="controller"
CONTROLLER_IP="controller"
CONTROLLER_PORT="4455"
UID="client4"
PWD="KML7NaC:@l.+5aB2"
LISTENING_IP="127.0.0.1"
LISTENING_PORT="5566"
DOMAIN_NAME="client-four"
CERTS_DIR="D:\\data\\certs\\client-four"
LOGS_DIR="logs"
LOG_LEVEL="debug"
DATA_DIR="d:\\data"