[env]
CONTROLLER_CERT_FILE="assets/certs/controller/ca.crt"
CONTROLLER_DOMAIN_NAME="localhost"
CONTROLLER_IP="localhost"
CONTROLLER_PORT="4455"
LISTENING_IP="127.0.0.1"
LISTENING_PORT="5567"
UID="client2"
PWD="U*?G&zYZoa9Buz1L"
DOMAIN_NAME="localhost"
CERTS_DIR="assets/certs/client"
LOGS_DIR="logs"
LOG_LEVEL="debug"