[env]
LISTENING_IP="127.0.0.1"
LISTENING_PORT="5567"
CONTROLLER_DOMAIN_NAME="localhost"
CONTROLLER_IP="localhost"
CONTROLLER_PORT="4455"
UID="client2"
PWD="U*?G&zYZoa9Buz1L"
LOGS_DIR="logs"
CERTS_DIR="assets/certs"
LOG_LEVEL="debug"