[env]
CONTROLLER_CERT_FILE="assets/certs/controller/ca.crt"
CONTROLLER_DOMAIN_NAME="localhost"
CONTROLLER_IP="localhost"
CONTROLLER_PORT="4455"
LISTENING_IP="127.0.0.1"
LISTENING_PORT="5566"
UID="client1"
PWD="338!Ac],U*[>GR9G"
CERTS_DIR="assets/certs/client"
DOMAIN_NAME="localhost"
LOGS_DIR="logs"
LOG_LEVEL="debug"