[env]
LISTENING_IP="127.0.0.1"
LISTENING_PORT="5566"
CONTROLLER_DOMAIN_NAME="localhost"
CONTROLLER_IP="localhost"
CONTROLLER_PORT="4455"
UID="client1"
PWD="338!Ac],U*[>GR9G"
LOGS_DIR="logs"
CERTS_DIR="assets/certs"
LOG_LEVEL="debug"