[env]
LISTENING_IP="127.0.0.1"
LISTENING_PORT="4466"
CONTROLLER_DOMAIN_NAME="localhost"
CONTROLLER_IP="127.0.0.1"
CONTROLLER_PORT="4455"
UID="proxy1"
PWD="igqX$F$MOE@GK1S6"
LOGS_DIR="logs"
CERTS_DIR="assets/certs"
LOG_LEVEL="debug"