[env]
CONTROLLER_CERT_FILE="assets/certs/controller/ca.crt"
CONTROLLER_DOMAIN_NAME="localhost"
CONTROLLER_IP="127.0.0.1"
CONTROLLER_PORT="4455"
LISTENING_IP="127.0.0.1"
LISTENING_PORT="4466"
UID="proxy1"
PWD="igqX$F$MOE@GK1S6"
DOMAIN_NAME="localhost"
CERTS_DIR="assets/certs/proxy"
LOGS_DIR="logs"
LOG_LEVEL="debug"