[env]
CONTROLLER_CERT_FILE="assets/cert/controller/ca.crt"
CONTROLLER_DOMAIN_NAME="localhost"
CONTROLLER_IP="localhost"
CONTROLLER_PORT="4455"
LISTENING_IP="127.0.0.1"
LISTENING_PORT="4467"
UID="proxy2"
PWD=".b}H0,&K!0SeBx79"
DOMAIN_NAME="localhost"
CERTS_DIR="assets/certs/proxy"
LOGS_DIR="logs"
LOG_LEVEL="debug"