[env]
LISTENING_IP="127.0.0.1"
LISTENING_PORT="4455"
DOMAIN_NAME="localhost"
UID="controller1"
PWD="L.KD<FCjkSA6AEg@"
LOGS_DIR="logs"
CERTS_DIR="assets/certs/controller"
LOG_LEVEL="debug"
REPOSITORY="0"
REDIS_URL="redis://127.0.0.1/"
MEMBERS_CSV_FILE="assets/members.csv"