[env]
LISTENING_IP="127.0.0.1"
LISTENING_PORT="4455"
CONTROLLER_DOMAIN_NAME="localhost"
CONTROLLER_IP="192.168.1.100"
CONTROLLER_PORT="8080"
UID="controller1"
PWD="L.KD<FCjkSA6AEg@"
LOGS_DIR="logs"
CERTS_DIR="assets/certs"
LOG_LEVEL="debug"
REPOSITORY="0"
REDIS_URL="redis://127.0.0.1/"
MEMBERS_CSV_FILE="assets/members.csv"